name: Lean Product Design
theme: just-the-docs
url: https://gsiener.github.io

permalink: pretty

exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
